# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: libcomps.spec

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: libcomps
# downstream (Fedora) RPM package name
downstream_package_name: libcomps

# To disable default jobs set them as empty
jobs: []
