---
name: Python CI
on: pull_request

jobs:
  python-build:
    name: Python Build
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo dnf -y install dnf-plugins-core python3-pip
          sudo dnf -y builddep libcomps.spec
          pip install --upgrade pip
          pip install pytest

      - name: Compile and Install
        run: pip install --user .

      - name: Test
        run: |
          pushd libcomps/src/python/tests/
          pytest --verbose --color=yes ./
          popd
